[settings]
max_title_length = 75
icon_size = 22

[settings.windows.screen_corner]
size = 25

[settings.background]
# Set values in the range of 0 to 1 (mathematically: [0, 1]).
red = 0
green = 0
blue = 0
alpha = 1

# This section determines how the classes of windows
# are viewed i
# Terminal such as foot.
[[common]]
find = ["foot"]
replace = "command-terminal"

# Browser such as Firefox.
[[common]]
find = ["firefox-nightly"]
replace = "internet-browser"

# Image viewer such as swayimg.
[[common]]
find = ["swayimg"]
replace = "any-image-viewer"

# Social media applications such as Telegram, Mastodon, ...
[[common]]
find = ["org.telegram.desktop", "vesktop"]
replace = "social-media"

# Streaming applications such as Stremio.
[[common]]
find = ["com.stremio.stremio"]
replace = "movie-streaming"

# Email applications such as Thunderbird.
[[common]]
find = ["thunderbird"]
replace = "email-manager"

# Screen-shoting applications such as Flameshot.
[[common]]
find = ["flameshot"]
replace = "tool-screenshot"

# Note-taking applications such as Obsidian.
[[common]]
find = ["obsidian"]
replace = "tool-notetaking"

# Design applications such as Inkscape.
[[common]]
find = ["org.inkscape.Inkscape"]
replace = "tool-designer"

# Video viewer applications such as mpv.
[[common]]
find = ["mpv"]
replace = "any-video-viewer"

# Digital art tool such as Gimp, Krita...
[[common]]
find = ["krita", "Gimp"]
replace = "digital-art-tool"
